# Refine Tracklets Module Configuration
# This module refines and merges tracklets using advanced algorithms

_target_: sn_gamestate.wrappers.gta_link.refine_tracklets_api.RefineTracklets

# Tracklet splitting parameters
use_split: true
eps: 0.5                    # DBSCAN epsilon parameter for splitting
min_samples: 3              # DBSCAN minimum samples parameter
max_k: 10                   # Maximum number of clusters for splitting
min_len: 30                 # Minimum tracklet length threshold

# Tracklet merging parameters
merge_dist_thres: 0.3       # Distance threshold for merging tracklets
spatial_factor: 1.0         # Spatial constraint factor
batch_size: 50              # Batch size for processing
use_batched_merge: true  # Use batched merging for efficiency
# Advanced parameters (optional)
# eps: 0.7                  # Higher eps for more aggressive splitting
# merge_dist_thres: 0.4     # Higher threshold for less aggressive merging
# spatial_factor: 1.5       # Larger spatial constraints
